import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const notoSerifBengali = Noto_Serif_Bengali({
  variable: "--font-noto-serif-bengali",
  subsets: ["latin", "bengali"],
});


export const metadata: Metadata = {
  title: "বাংলা সংবাদ ২৪",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
data-theme="light"
      lang="en, bn"
      
      className={`${notoSerifBengali .className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header />  
        {children}
        </body>
    </html>
  );
}
